version: "3.7"
services:
  nifi:
    image: apache/nifi:1.10.0
    ports:
      - "8080:8080"
    volumes:
      - ./data/conf/archive:/opt/nifi/nifi-current/conf/archive
      - ./data/database_repository:/opt/nifi/nifi-current/database_repository
      - ./data/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./data/content_repository:/opt/nifi/nifi-current/content_repository
      - ./data/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./data/state:/opt/nifi/nifi-current/state
      - ./data/logs:/opt/nifi/nifi-current/logs
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_JVM_HEAP_INIT=8g
      - NIFI_JVM_HEAP_MAX=16g
    hostname: nifi
    restart: unless-stopped
